collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1079484
color:
  saturation: 0.4828142
  brandStrength: 0.9543501
  lightness: 0.4205156
  brandColors:
    - '#FFFFFF'
    - '#020101'
    - '#660001'
    - '#B52714'
    - '#393939'
  rhythmicContrast: 1
layout_spectrum: 1
name: 'Anointed Generation '
